export const SITE_CONTENT = {
  es: {
    nav: {
      webs: 'Webs',
      manager: 'Gestor',
      route: 'Ver recorrido',
      problem: 'El reto',
      differences: 'Producto',
      demos: 'Demos',
      plans: 'Planes',
      support: 'Implantación',
      faq: 'Preguntas',
      contact: 'Solicitar demo',
      language: 'EN',
    },
    hero: {
      eyebrow: 'Reservas, grupos y eventos',
      beforeHighlight: 'La sala ',
      highlight: 'manda.',
      afterHighlight: ' También online.',
      promise: 'Una sola disponibilidad para todo el servicio.',
      body: 'Mesas, menús, grupos y eventos avanzan con la sala real delante. Lo que se ofrece online se bloquea donde corresponde, sin reconstruir el día entre herramientas.',
      support: 'La implantación se define con Logic2B a partir de tu operativa real.',
      primary: 'Abrir la demo · 2 min',
      secondary: 'Hablar de mi operativa',
      webAction: 'Ver web demo',
      guidedAction: 'Recorrido guiado',
      managerAction: 'Probar el gestor',
      proofLabel: 'Tres formas de entrar',
      portfolioLabel: 'Webs con identidad propia',
      portfolioAction: 'Abrir web',
      briefTitle: '¿Quieres verlo aplicado a tu restaurante?',
      briefBody: 'Indica tu correo y completa el contexto en el siguiente paso.',
      briefEmail: 'Correo profesional',
      briefPrivacy: 'Acepto que Logic2B use este correo para responder a esta solicitud.',
      briefSubmit: 'Continuar',
      briefBoundary: 'El correo no se envía a Logic2B en este paso.',
      note: 'Escenario navegable de Solane · Datos ficticios, sin cobros reales',
      capture: { title: '¿Por dónde empezar?', body: 'Déjanos un correo profesional y te enseñamos el recorrido que encaja mejor.', name: 'Tu nombre', email: 'Tu correo profesional', level: 'Punto de partida', privacy: 'Acepto que Logic2B use estos datos para responder.', submit: 'Ver mi punto de partida', restaurant: 'Captación breve desde Logic Reserva', message: 'Quiero conocer el punto de partida de Logic Reserva.' },
    },
    ecosystem: {
      eyebrow: 'Ecosistema con contexto',
      title: 'Cada conexión tiene un estado.',
      intro: 'La demo deja claro qué está disponible, qué se demuestra y qué necesitaría un proyecto real antes de activarse.',
      items: [
        { name: 'Web propia', state: 'Demostrado', body: 'Brasca, Vedra y Solane muestran recorridos con identidad de restaurante.' },
        { name: 'Pagos y depósitos', state: 'Por proyecto', body: 'La regla de depósito se informa y simula; no se realiza ningún cobro.' },
        { name: 'Asistentes y automatización', state: 'Demostrativo', body: 'Solane enseña decisiones deterministas sin IA conectada ni proveedor externo.' },
      ],
    },
    journey: {
      eyebrow: 'Del primer clic a la decisión de sala',
      title: 'Siete momentos, una misma disponibilidad.',
      intro: 'La plataforma acompaña el servicio entero: cada paso conserva el contexto que el siguiente equipo necesita para actuar.',
      steps: [
        { number: '01', label: 'Web', title: 'Tu marca abre la conversación.', body: 'El cliente llega a una web propia, con la carta y el tono del restaurante.' },
        { number: '02', label: 'Disponibilidad', title: 'La mesa disponible es la que puedes servir.', body: 'Turnos, tamaño de grupo y mesas reales filtran lo que se ofrece online.' },
        { number: '03', label: 'Reserva', title: 'La solicitud llega con contexto.', body: 'Datos, menú, origen y estado entran juntos en el recorrido operativo.' },
        { number: '04', label: 'Servicio', title: 'Sala trabaja sobre el día real.', body: 'El equipo ve el plano, las reservas y los cambios antes de abrir puertas.' },
        { number: '05', label: 'Garantía y cobro', title: 'Las condiciones se explican antes.', body: 'Depósitos y reglas se informan y simulan; cualquier cobro real se define por proyecto.' },
        { number: '06', label: 'Comunicación', title: 'Cada respuesta deja seguimiento.', body: 'Confirmaciones y solicitudes de cambio quedan preparadas para una acción humana.' },
        { number: '07', label: 'Decisión', title: 'La operación aprende del servicio.', body: 'Informes, escenarios y señales consultivas ayudan a decidir qué ordenar después.' },
      ],
    },
    moments: {
      eyebrow: 'Cinco puertas al producto',
      title: 'Cada equipo ve el siguiente movimiento.',
      intro: 'Abre un momento para entender su resultado, las capacidades demostradas y el límite que todavía requiere una implantación.',
      tabsLabel: 'Momentos del producto',
      limitLabel: 'Límite honesto',
      items: [
        { id: 'web', label: 'Web', level: 'Básico', result: 'Una web que convierte sin sacar al cliente de tu marca.', capabilities: ['Identidad propia y carta', 'Solicitud de mesa contextual', 'Recorrido preparado para crecer'], limit: 'Brasca recibe la solicitud en la demo; el envío real por email requiere un proyecto habilitado.', evidence: 'Evidencia: web de Brasca', action: 'Abrir evidencia web' },
        { id: 'reservas', label: 'Reservas', level: 'Gestión', result: 'Una reserva pasa de la web al espacio de trabajo.', capabilities: ['Turnos de 15 minutos', 'Mesas y menús vinculados', 'Estados y origen visibles'], limit: 'Vedra trabaja con fixtures locales; cuentas, multiusuario y migración se definirían aparte.', evidence: 'Evidencia: recorrido de reserva Vedra', action: 'Abrir evidencia de reservas' },
        { id: 'sala', label: 'Sala', level: 'Gestión', result: 'El equipo decide con el plano delante.', capabilities: ['Plano por sala', 'Transiciones de servicio', 'Lista de espera local'], limit: 'Los roles de la demo orientan la experiencia, pero no sustituyen autenticación ni permisos de producción.', evidence: 'Evidencia: gestor de Vedra', action: 'Abrir evidencia de sala' },
        { id: 'grupos', label: 'Grupos y eventos', level: 'Inteligente', result: 'El evento consume la capacidad que realmente necesita.', capabilities: ['Aforo y mesas compartidos', 'Menú y condiciones trazables', 'Privatización guiada'], limit: 'Las señales y depósitos se simulan; proveedor, contrato y cobro se validan por proyecto.', evidence: 'Evidencia: eventos de Solane', action: 'Abrir evidencia de eventos' },
        { id: 'operativa', label: 'Operativa', level: 'Inteligente', result: 'Los informes convierten el servicio en una conversación.', capabilities: ['CRM y exportación local', 'Escenarios hipotéticos', 'Señales consultivas explicables'], limit: 'Los datos son ficticios y locales; no son contabilidad, predicción ni una decisión automática.', evidence: 'Evidencia: informes de Solane', action: 'Abrir evidencia operativa' },
      ],
    },
    connections: {
      eyebrow: 'Conexiones con contexto',
      title: 'La plataforma no promete lo que aún no está conectado.',
      intro: 'Herramientas, pagos y asistentes aparecen como decisiones de alcance, con su madurez visible y su límite explicado.',
      items: [
        { family: 'Herramientas', state: 'Por proyecto', title: 'Web, dominio y datos deben encajar.', body: 'La implantación define qué se conecta, quién mantiene cada sistema y qué ocurre si se cambia de proveedor.' },
        { family: 'Pagos', state: 'Por proyecto', title: 'Cobrar exige una decisión aparte.', body: 'La demo muestra condiciones y depósitos ficticios. No hay tarjetas, cobros ni conciliación activa.' },
        { family: 'Asistentes', state: 'Demostrativo', title: 'Automatizar no significa ocultar la decisión.', body: 'Solane presenta señales deterministas y revisables, sin modelo conectado, credenciales ni acciones externas.' },
      ],
    },
    ecosystem: {
      eyebrow: 'Ecosistema previsto',
      title: 'Conecta el servicio sin convertir cada herramienta en otra isla.',
      body: 'Cada marca indica su estado real dentro de esta demostración. Visible no significa integrada, y cualquier conexión operativa se valida por proyecto.',
      label: 'Estado de herramientas y conexiones',
      items: [
        { name: 'Resend', detail: 'Formulario comercial', status: 'Conectado', tone: 'connected' },
        { name: 'Cloudflare', detail: 'Entrega y seguridad web', status: 'Conectado', tone: 'connected' },
        { name: 'Stripe', detail: 'Cobro ficticio en la demo', status: 'Demostrativo', tone: 'demo' },
        { name: 'WhatsApp', detail: 'Contacto comercial', status: 'Visible', tone: 'visible' },
        { name: 'Google Maps', detail: 'Ubicación y contexto', status: 'Previsto', tone: 'planned' },
        { name: 'Zapier', detail: 'Automatización por proyecto', status: 'Previsto', tone: 'planned' },
      ],
    },
    productFlow: {
      eyebrow: 'De la visita a la decisión',
      title: 'La reserva no termina cuando se confirma.',
      intro: 'Siete pasos comparten el mismo contexto para que la promesa online llegue entera a sala y vuelva convertida en una decisión útil.',
      label: 'Recorrido completo de producto en siete pasos',
      previous: 'Ver paso anterior',
      next: 'Ver paso siguiente',
      steps: [
        { id: 'web', label: 'Web', title: 'La intención nace dentro de tu marca.', body: 'Carta, ocasión y llamada a reservar conviven en una experiencia propia.' },
        { id: 'availability', label: 'Disponibilidad', title: 'Solo se ofrece lo que la sala puede asumir.', body: 'Turno, tamaño de grupo, mesas y eventos responden sobre una capacidad común.' },
        { id: 'booking', label: 'Reserva', title: 'El contexto entra antes que el comensal.', body: 'Menú, preferencias y origen acompañan la solicitud sin reconstruir mensajes.' },
        { id: 'service', label: 'Servicio', title: 'Sala asigna y actúa desde una sola vista.', body: 'Agenda, plano, espera y estados muestran qué necesita atención ahora.' },
        { id: 'guarantee', label: 'Garantía y cobro', title: 'El compromiso queda explicado y trazable.', body: 'La demo calcula señales ficticias; cualquier proveedor real se acuerda por proyecto.' },
        { id: 'communication', label: 'Comunicación', title: 'Cada contacto parte del estado correcto.', body: 'Confirmaciones y seguimientos se preparan con contexto, sin fingir envíos automáticos.' },
        { id: 'decision', label: 'Decisión', title: 'La operación devuelve señales que se pueden explicar.', body: 'Informes y prioridades locales ayudan a decidir sin ejecutar acciones por su cuenta.' },
      ],
    },
    platform: {
      eyebrow: 'Cinco momentos de plataforma',
      title: 'Una sola historia, vista desde quien tiene que actuar.',
      intro: 'Cada momento parte de una pantalla real de la demostración. Las capacidades están abiertas para probarlas y el límite se muestra junto a la promesa.',
      tabsLabel: 'Momentos de la plataforma',
      resultLabel: 'Resultado',
      capabilitiesLabel: 'Qué demuestra',
      limitLabel: 'Límite actual',
      evidenceLabel: 'Evidencia real del producto',
      items: [
        { id: 'web', label: 'Web', result: 'La reserva empieza sin abandonar la identidad del restaurante.', capabilities: ['Narrativa y carta orientadas a conversión', 'Solicitud integrada en la web propia', 'Diseño responsive con marca diferenciada'], limit: 'Dominio, contenidos, SEO y recepción real de solicitudes se definen en cada implantación.', status: 'Demostrativo', tone: 'demo', image: '01-brasca-marca', alt: 'Portada responsive del restaurante ficticio Brasca con llamada a reservar', href: '/demos/brasca/', action: 'Abrir la web de Brasca' },
        { id: 'bookings', label: 'Reservas', result: 'La disponibilidad responde antes de prometer una mesa.', capabilities: ['Turnos y tamaños de grupo', 'Menús opcionales o cerrados', 'Contexto de la solicitud hasta confirmación'], limit: 'El inventario es local y ficticio; no está conectado a un motor o TPV de un restaurante real.', status: 'Demostrativo', tone: 'demo', image: '03-vedra-reserva', alt: 'Motor de Vedra con horario y menú de grupo seleccionados', href: '/demos/vedra/', action: 'Probar una reserva en Vedra' },
        { id: 'floor', label: 'Sala', result: 'El equipo ve reservas, mesas y bloqueos sobre el mismo servicio.', capabilities: ['Agenda operativa del día', 'Plano con asignación de mesas', 'Espera y estados de servicio'], limit: 'No existe todavía operación multiusuario ni sincronización compartida: el estado vive en este navegador.', status: 'Demostrativo', tone: 'demo', image: '05-solane-inventario', alt: 'Plano de Solane con reservas y evento compartiendo el inventario de mesas', href: '/demos/solane/gestion/?vista=plano', action: 'Abrir el plano de Solane' },
        { id: 'groups', label: 'Grupos y eventos', result: 'La oportunidad comercial deja de competir a ciegas con la sala.', capabilities: ['Solicitud y propuesta con condiciones', 'Menús, señal y seguimiento del grupo', 'Bloqueo del espacio compartido'], limit: 'La señal es simulada y no mueve dinero; mensajes, contratos y proveedores se acuerdan por proyecto.', status: 'Demostrativo', tone: 'demo', image: '07-solane-privatizacion', alt: 'Privatización de Solane bloqueada después de una propuesta y señal simulada', href: '/demos/solane/gestion/?vista=privatizaciones', action: 'Ver la privatización' },
        { id: 'operations', label: 'Operativa', result: 'Dirección prioriza con señales que puede revisar y explicar.', capabilities: ['Informes de servicio reproducibles', 'Score local con factores visibles', 'Seguimientos preparados para decisión humana'], limit: 'Las señales no son predicciones y ninguna recomendación contacta, cancela o cambia una reserva automáticamente.', status: 'Demostrativo', tone: 'demo', image: '08-solane-riesgo', alt: 'Informe de Solane con reservas priorizadas y factores explicables', href: '/demos/solane/gestion/?vista=informes', action: 'Revisar los informes' },
      ],
    },
    connections: {
      eyebrow: 'Conexiones con contexto',
      title: 'Conectar solo tiene sentido cuando cada sistema sabe qué está ocurriendo.',
      intro: 'El estado describe esta demostración, no la capacidad general de cada proveedor. Cualquier intercambio operativo, dato o automatización necesita un alcance aprobado.',
      label: 'Familias de conexiones y estado de madurez',
      families: [
        { id: 'tools', title: 'Herramientas', body: 'Canales y servicios que sostienen la experiencia o podrían recibir contexto operativo.', items: [
          { name: 'Resend', detail: 'Entrega del formulario comercial autorizado', status: 'Conectado', tone: 'connected' },
          { name: 'Cloudflare', detail: 'Web, seguridad y ejecución de la demo', status: 'Conectado', tone: 'connected' },
          { name: 'WhatsApp', detail: 'Circuitos de reservas y seguimiento', status: 'Por proyecto', tone: 'project' },
        ] },
        { id: 'payments', title: 'Pagos', body: 'Garantías, señales y cobros dependen de política, proveedor y conciliación.', items: [
          { name: 'Stripe', detail: 'Pasarela ficticia del recorrido Solane', status: 'Demostrativo', tone: 'demo' },
          { name: 'Redsys', detail: 'Alternativa de cobro para evaluar', status: 'Previsto', tone: 'planned' },
          { name: 'Garantías', detail: 'Importe, devolución y excepciones', status: 'Por proyecto', tone: 'project' },
        ] },
        { id: 'assistants', title: 'Asistentes con contexto', body: 'Las sugerencias deben enseñar sus señales y devolver siempre la decisión al equipo.', items: [
          { name: 'Prioridad de no-show', detail: 'Cálculo local con factores explicables', status: 'Demostrativo', tone: 'demo' },
          { name: 'Zapier', detail: 'Orquestación futura entre herramientas', status: 'Previsto', tone: 'planned' },
          { name: 'TPV y CRM', detail: 'Datos externos y acciones permitidas', status: 'Por proyecto', tone: 'project' },
        ] },
      ],
    },
    differences: {
      eyebrow: 'Un servicio. Una disponibilidad.',
      title: 'Dos operativas que ya no compiten entre sí.',
      intro: 'La reserva diaria y los eventos necesitan recorridos distintos. Comparten la misma capacidad, las mismas mesas y una decisión visible para sala.',
      paths: [
        { id: 'restaurant', eyebrow: 'Servicio diario', title: 'La disponibilidad que publicas nace de la sala.', body: 'Cada solicitud responde a turno, mesa, tamaño de grupo y menú. El cliente reserva dentro de tu marca y el equipo recibe el contexto listo para actuar.', points: ['Mesas y turnos conectados', 'Menús opcionales o cerrados', 'Estados claros antes del servicio'], action: 'Ver reservas de restaurante' },
        { id: 'events', eyebrow: 'Grupos y eventos', title: 'El evento deja de vivir fuera del servicio.', body: 'Solicitud, propuesta, señal y bloqueo del espacio avanzan juntos. Cuando el evento ocupa mesas, la disponibilidad ordinaria responde.', points: ['Solicitud y propuesta con contexto', 'Señal y condiciones trazables en la demo', 'Bloqueo del espacio compartido'], action: 'Ver grupos y eventos' },
      ],
    },
    demos: {
      eyebrow: 'La prueba está abierta',
      title: 'No te lo contamos. Te lo dejamos abierto.',
      intro: 'Tres operaciones ficticias muestran tres puntos de partida. Entra, reserva, organiza un servicio y comprueba qué cambia cuando todo comparte contexto.',
      items: [
        { slug: 'solane', name: 'Solane', level: 'Inteligente', title: 'El evento también ocupa mesa', body: 'Eventos, depósitos y privatizaciones comparten el inventario del servicio. Publica una cena y comprueba cómo responde la disponibilidad.', action: 'Entrar en Solane', alt: 'Gestión de una privatización que bloquea el espacio en el inventario de Solane' },
        { slug: 'vedra', name: 'Vedra', level: 'Gestión', title: 'Ordena el servicio antes de abrir', body: 'Reservas, grupos, mesas y clientes llegan al mismo espacio de trabajo para que sala no tenga que reconstruir el día.', action: 'Entrar en Vedra', alt: 'Comedor luminoso del restaurante ficticio Vedra' },
        { slug: 'brasca', name: 'Brasca', level: 'Básico', title: 'Recupera una web que sí trabaja', body: 'Un bistró de barrio recibe solicitudes con su propia identidad y sin ceder el primer contacto.', action: 'Entrar en Brasca', alt: 'Mesa preparada en el bistró ficticio Brasca' },
      ],
    },
    human: {
      eyebrow: 'Implantación, no autoservicio',
      title: 'Tu operativa marca las reglas. Logic2B diseña el encaje.',
      body: 'Si el proyecto avanza, el alcance se acuerda sobre tus turnos, mesas, grupos, eventos y canales. La demostración enseña el recorrido; la implantación real se valida por proyecto.',
      items: [
        { number: '01', title: 'Leemos el servicio', body: 'Revisamos lo que ya funciona y dónde se pierde contexto antes de abrir puertas.' },
        { number: '02', title: 'Definimos el alcance', body: 'Acordamos recorridos, reglas e integraciones antes de convertir una pantalla en promesa.' },
        { number: '03', title: 'Preparamos los datos', body: 'Acordamos qué información existe, quién la posee y qué necesita migrarse antes de probar el recorrido.' },
        { number: '04', title: 'Configuramos y validamos', body: 'Convertimos reglas, permisos e integraciones en una configuración revisable por las personas que prestan el servicio.' },
        { number: '05', title: 'Publicamos con el equipo', body: 'Formación, dominio y salida se preparan con un plan claro, sin presentar una capacidad como activa antes de tiempo.' },
        { number: '06', title: 'Acompañamos la operación', body: 'Mantenimiento, mejoras y límites quedan documentados para que el siguiente cambio también tenga un responsable.' },
      ],
      closing: 'Primero el servicio. Después, la tecnología que tendría sentido desarrollar o integrar.',
      action: 'Revisar mi operativa',
    },
    faq: {
      eyebrow: 'Antes de mover una sola mesa',
      title: 'Las dudas que sí cambian la decisión.',
      items: [
        { question: '¿Qué estoy viendo exactamente?', answer: 'Una demostración comercial navegable. El estado vive en tu navegador y no existen todavía cuentas, base de datos multi-tenant, cobros ni integraciones de restaurante.' },
        { question: '¿Qué se define antes de implantar?', answer: 'Alcance, datos, permisos, proveedores, migración, integraciones y soporte. Ninguna capacidad se considera activa por aparecer en una pantalla.' },
        { question: '¿El dominio y las cuentas siguen siendo del restaurante?', answer: 'La titularidad y los accesos se documentan antes de publicar. El restaurante debe conservar control autorizado sobre dominio, DNS, correo y cuentas de proveedores según lo acordado.' },
        { question: '¿Puede convivir con mi motor de reservas actual?', answer: 'Puede evaluarse, pero no se presupone una integración. Primero se identifica el cuello de botella y después se valida qué sistema conserva cada responsabilidad y qué intercambio de datos tendría sentido.' },
        { question: '¿Cuánto tarda y qué dificultad tiene la puesta en marcha?', answer: 'Depende de datos, reglas, contenidos, proveedores e integraciones. El calendario y los criterios de aceptación se concretan en propuesta después de revisar la operativa real.' },
        { question: '¿Cómo se migran y protegen los datos?', answer: 'Se acuerdan fuentes, formato, fecha de corte, validación, acceso, retención, exportación y salida. La demo no contiene datos reales ni sustituye la revisión de RGPD de cada proyecto.' },
        { question: '¿Cómo se plantean depósitos, pagos y no-shows?', answer: 'La demo muestra información previa, aceptación y desglose con datos ficticios. Proveedor, política, conciliación, devoluciones y cualquier cobro real se validan y documentan por proyecto.' },
        { question: '¿Tengo que cambiar toda mi operativa?', answer: 'No. La conversación empieza por el cuello de botella actual y por lo que tu equipo ya sabe hacer. El alcance comercial se acuerda antes de desarrollar o activar nada.' },
        { question: '¿Qué se necesita para publicar?', answer: 'Dominio, datos, responsables, permisos, validación y un plan de salida. La guía técnica ayuda a ordenar esas decisiones; la demo no publica cambios por sí sola.' },
        { question: '¿Tengo que cambiar el motor que ya uso?', answer: 'No necesariamente. Primero se identifica dónde se pierde contexto y qué debe conservarse. La convivencia o sustitución de un proveedor forma parte del alcance acordado.' },
      ],
    },
    lead: {
      eyebrow: 'Empieza con una conversación, no con una cuenta',
      title: 'Cuéntanos qué quieres ordenar. Te devolvemos un punto de partida.',
      body: 'Logic2B revisará la operativa que compartas y preparará un mapa inicial de alcance para reservas, grupos, eventos y sala.',
      fields: { name: 'Nombre', restaurant: 'Restaurante', email: 'Correo profesional', phone: 'Teléfono (opcional)', level: 'Qué quieres ordenar primero', message: '¿Qué ocurre hoy? (opcional)', privacy: 'He leído la política de privacidad y acepto que Logic2B use estos datos para responder.' },
      priorities: [{ value: 'basico', label: 'Reserva directa en mi web' }, { value: 'gestion', label: 'Servicio diario y grupos' }, { value: 'inteligente', label: 'Eventos y privatizaciones' }],
      submit: 'Enviar solicitud',
      disabled: 'Envío deshabilitado en esta demo. No se ha enviado ni guardado ningún dato. Puedes contactar directamente con Logic2B por WhatsApp.',
      invalid: 'Revisa los campos obligatorios y la aceptación de privacidad.',
      failure: 'No se ha podido conectar. No se ha enviado ni guardado ningún dato.',
      success: 'Solicitud entregada a Logic2B. Conserva la referencia por si necesitas consultarnos.',
      limited: 'Has alcanzado el límite temporal de solicitudes. Espera un minuto o contacta por WhatsApp.',
      whatsapp: 'Hablar por WhatsApp',
    },
    cookies: {
      text: 'Esta web no carga analítica. Solo guardamos tu preferencia para no volver a preguntarte.',
      accept: 'Aceptar analítica futura',
      reject: 'Solo necesarias',
    },
    footer: {
      line: 'Una propuesta de reservas, grupos y eventos construida alrededor de la sala real.',
      plans: 'Planes',
      restaurants: 'Restaurantes',
      groups: 'Grupos y eventos',
      legal: 'Legal',
      privacy: 'Privacidad',
      cookies: 'Cookies',
      demo: 'Demostración comercial · No es un servicio en producción',
    },
  },
  en: {
    nav: { webs: 'Websites', manager: 'Manager', route: 'View journey', problem: 'The challenge', differences: 'Product', demos: 'Demos', plans: 'Plans', support: 'Implementation', faq: 'Questions', contact: 'Request a demo', language: 'ES' },
    hero: { eyebrow: 'Bookings, groups and events', beforeHighlight: 'The floor ', highlight: 'leads.', afterHighlight: ' Online too.', promise: 'One availability view for the whole service.', body: 'Tables, menus, groups and events move with the real floor in view. What is offered online is blocked in the right place, without rebuilding the day across tools.', support: 'Implementation is defined with Logic2B around your real operation.', primary: 'Open the demo · 2 min', secondary: 'Discuss my operation', webAction: 'View website demo', guidedAction: 'Guided journey', managerAction: 'Try the manager', proofLabel: 'Three ways in', portfolioLabel: 'Websites with their own identity', portfolioAction: 'Open website', briefTitle: 'Want to see it applied to your restaurant?', briefBody: 'Enter your email and complete the context in the next step.', briefEmail: 'Work email', briefPrivacy: 'I agree that Logic2B may use this email to reply to this request.', briefSubmit: 'Continue', briefBoundary: 'Your email is not sent to Logic2B at this step.', note: 'Navigable Solane scenario · Fictional data, no real charges' },
    ecosystem: { eyebrow: 'Planned ecosystem', title: 'Connect service without turning every tool into another island.', body: 'Each brand shows its real status in this demonstration. Visible does not mean integrated, and every operational connection is validated per project.', label: 'Status of tools and connections', items: [{ name: 'Resend', detail: 'Commercial form', status: 'Connected', tone: 'connected' }, { name: 'Cloudflare', detail: 'Web delivery and security', status: 'Connected', tone: 'connected' }, { name: 'Stripe', detail: 'Fictional demo payment', status: 'Demonstrative', tone: 'demo' }, { name: 'WhatsApp', detail: 'Commercial contact', status: 'Visible', tone: 'visible' }, { name: 'Google Maps', detail: 'Location and context', status: 'Planned', tone: 'planned' }, { name: 'Zapier', detail: 'Automation per project', status: 'Planned', tone: 'planned' }] },
    productFlow: { eyebrow: 'From visit to decision', title: 'A booking does not end when it is confirmed.', intro: 'Seven steps share the same context, so the online promise reaches the floor intact and returns as a useful decision.', label: 'Complete seven-step product journey', previous: 'View previous step', next: 'View next step', steps: [
      { id: 'web', label: 'Website', title: 'Intent starts inside your brand.', body: 'Menu, occasion and the booking action live together in an owned experience.' },
      { id: 'availability', label: 'Availability', title: 'Only what the floor can handle is offered.', body: 'Turn, party size, tables and events respond against shared capacity.' },
      { id: 'booking', label: 'Booking', title: 'Context arrives before the guest.', body: 'Menu, preferences and source travel with the enquiry without rebuilding messages.' },
      { id: 'service', label: 'Service', title: 'The floor team assigns and acts from one view.', body: 'Agenda, floor plan, waitlist and states show what needs attention now.' },
      { id: 'guarantee', label: 'Guarantee and payment', title: 'The commitment stays explained and traceable.', body: 'The demo calculates fictional guarantees; any real provider is agreed per project.' },
      { id: 'communication', label: 'Communication', title: 'Every contact starts from the right state.', body: 'Confirmations and follow-ups are prepared with context, without pretending to send automatically.' },
      { id: 'decision', label: 'Decision', title: 'Operations return signals that can be explained.', body: 'Local reports and priorities support decisions without taking action on their own.' },
    ] },
    platform: { eyebrow: 'Five platform moments', title: 'One story, seen by the person who needs to act.', intro: 'Every moment starts from a real screen in the demonstration. The capabilities are open to try, and the limit appears beside the promise.', tabsLabel: 'Platform moments', resultLabel: 'Outcome', capabilitiesLabel: 'What it demonstrates', limitLabel: 'Current limit', evidenceLabel: 'Real product evidence', items: [
      { id: 'web', label: 'Website', result: 'The booking starts without leaving the restaurant identity.', capabilities: ['Conversion-led story and menu', 'Enquiry embedded in the owned website', 'Responsive design with a distinct brand'], limit: 'Domain, content, SEO and real enquiry delivery are defined for each implementation.', status: 'Demonstrative', tone: 'demo', image: '01-brasca-marca', alt: 'Responsive home page for the fictional Brasca restaurant with a booking call to action', href: '/demos/brasca/', action: 'Open the Brasca website' },
      { id: 'bookings', label: 'Bookings', result: 'Availability responds before promising a table.', capabilities: ['Turns and party sizes', 'Optional or fixed menus', 'Enquiry context through confirmation'], limit: 'Inventory is local and fictional; it is not connected to a real restaurant engine or POS.', status: 'Demonstrative', tone: 'demo', image: '03-vedra-reserva', alt: 'Vedra booking engine with a time and group menu selected', href: '/demos/vedra/', action: 'Try a booking in Vedra' },
      { id: 'floor', label: 'Floor', result: 'The team sees bookings, tables and blocks across one service.', capabilities: ['Operational agenda for the day', 'Floor plan with table assignment', 'Waitlist and service states'], limit: 'There is no multi-user operation or shared synchronisation yet: state lives in this browser.', status: 'Demonstrative', tone: 'demo', image: '05-solane-inventario', alt: 'Solane floor plan with bookings and an event sharing table inventory', href: '/demos/solane/gestion/?vista=plano', action: 'Open the Solane floor plan' },
      { id: 'groups', label: 'Groups and events', result: 'The commercial opportunity no longer competes blindly with the floor.', capabilities: ['Enquiry and proposal with terms', 'Menus, deposit and group follow-up', 'Shared space blocking'], limit: 'The deposit is simulated and moves no money; messages, contracts and providers are agreed per project.', status: 'Demonstrative', tone: 'demo', image: '07-solane-privatizacion', alt: 'Solane private hire blocked after a proposal and simulated deposit', href: '/demos/solane/gestion/?vista=privatizaciones', action: 'View the private hire journey' },
      { id: 'operations', label: 'Operations', result: 'Management prioritises using signals it can review and explain.', capabilities: ['Reproducible service reports', 'Local score with visible factors', 'Follow-ups prepared for human decision'], limit: 'Signals are not predictions, and no recommendation contacts, cancels or changes a booking automatically.', status: 'Demonstrative', tone: 'demo', image: '08-solane-riesgo', alt: 'Solane report with prioritised bookings and explainable factors', href: '/demos/solane/gestion/?vista=informes', action: 'Review the reports' },
    ] },
    connections: { eyebrow: 'Connections with context', title: 'A connection only helps when every system knows what is happening.', intro: 'The status describes this demonstration, not each provider’s general capability. Any operational exchange, data or automation needs an approved scope.', label: 'Connection families and maturity status', families: [
      { id: 'tools', title: 'Tools', body: 'Channels and services that support the experience or could receive operational context.', items: [
        { name: 'Resend', detail: 'Delivery for the authorised commercial form', status: 'Connected', tone: 'connected' },
        { name: 'Cloudflare', detail: 'Website, security and demo runtime', status: 'Connected', tone: 'connected' },
        { name: 'WhatsApp', detail: 'Booking and follow-up journeys', status: 'Per project', tone: 'project' },
      ] },
      { id: 'payments', title: 'Payments', body: 'Guarantees, deposits and charges depend on policy, provider and reconciliation.', items: [
        { name: 'Stripe', detail: 'Fictional gateway in the Solane journey', status: 'Demonstrative', tone: 'demo' },
        { name: 'Redsys', detail: 'Payment alternative to assess', status: 'Planned', tone: 'planned' },
        { name: 'Guarantees', detail: 'Amount, refunds and exceptions', status: 'Per project', tone: 'project' },
      ] },
      { id: 'assistants', title: 'Context-aware assistants', body: 'Suggestions must show their signals and always return the decision to the team.', items: [
        { name: 'No-show priority', detail: 'Local calculation with explainable factors', status: 'Demonstrative', tone: 'demo' },
        { name: 'Zapier', detail: 'Future orchestration between tools', status: 'Planned', tone: 'planned' },
        { name: 'POS and CRM', detail: 'External data and permitted actions', status: 'Per project', tone: 'project' },
      ] },
    ] },
    differences: { eyebrow: 'One service. One availability view.', title: 'Two operations that no longer compete.', intro: 'Daily bookings and events need different journeys. They share the same capacity, the same tables and one decision visible to the floor team.', paths: [{ id: 'restaurant', eyebrow: 'Daily service', title: 'Published availability starts with the floor.', body: 'Every enquiry follows turns, tables, party size and menu. Guests book inside your brand and the team receives context ready for action.', points: ['Connected tables and turns', 'Optional or fixed menus', 'Clear states before service'], action: 'See restaurant bookings' }, { id: 'events', eyebrow: 'Groups and events', title: 'The event stops living outside service.', body: 'Enquiry, proposal, deposit and space block move together. When the event uses tables, ordinary availability responds.', points: ['Context-rich enquiry and proposal', 'Traceable demo deposit and terms', 'Shared space blocking'], action: 'See groups and events' }] },
    demos: { eyebrow: 'The proof is open', title: 'We do not just describe it. We leave it open.', intro: 'Three fictional operations show three starting points. Step in, book, organise a service and see what changes when everything shares context.', items: [{ slug: 'solane', name: 'Solane', level: 'Intelligent', title: 'The event takes up tables too', body: 'Events, deposits and private hire share service inventory. Publish a dinner and watch availability respond.', action: 'Enter Solane', alt: 'Private-hire workflow blocking the space in Solane’s shared inventory' }, { slug: 'vedra', name: 'Vedra', level: 'Management', title: 'Organise service before opening', body: 'Bookings, groups, tables and guests reach one workspace so the floor team does not rebuild the day.', action: 'Enter Vedra', alt: 'Bright dining room at the fictional Vedra restaurant' }, { slug: 'brasca', name: 'Brasca', level: 'Basic', title: 'Make your website work again', body: 'A neighbourhood bistro receives enquiries in its own identity without giving away the first contact.', action: 'Enter Brasca', alt: 'A prepared table at the fictional Brasca bistro' }] },
    human: { eyebrow: 'Implementation, not self-service', title: 'Your operation sets the rules. Logic2B designs the fit.', body: 'If the project moves forward, scope is agreed around your turns, tables, groups, events and channels. The demo shows the journey; real implementation is validated per project.', items: [{ number: '01', title: 'Read the service', body: 'We review what already works and where context gets lost before doors open.' }, { number: '02', title: 'Define the scope', body: 'We agree journeys, rules and integrations before turning a screen into a promise.' }, { number: '03', title: 'Validate what launch would require', body: 'Data, permissions, payments and providers would require a separate client deployment, developed and approved for that scope.' }], closing: 'Service first. Then the technology that would make sense to develop or integrate.', action: 'Review my operation' },
    faq: { eyebrow: 'Before moving a single table', title: 'The questions that change the decision.', items: [{ question: 'What exactly am I looking at?', answer: 'A navigable commercial demonstration. State lives in your browser; there are no production accounts, multi-tenant database, payments or restaurant integrations yet.' }, { question: 'What is defined before implementation?', answer: 'Scope, data, permissions, providers, migration, integrations and support. A capability is not active merely because it appears on a screen.' }, { question: 'Do the domain and provider accounts remain with the restaurant?', answer: 'Ownership and access are documented before publication. The restaurant should retain authorised control over its domain, DNS, email and provider accounts as agreed.' }, { question: 'Can it coexist with my current booking engine?', answer: 'It can be assessed, but an integration is not assumed. We first identify the bottleneck, then validate which system keeps each responsibility and which data exchange makes sense.' }, { question: 'How long does launch take and how difficult is it?', answer: 'That depends on data, rules, content, providers and integrations. Timeline and acceptance criteria are defined in the proposal after reviewing the real operation.' }, { question: 'How are data migrated and protected?', answer: 'Sources, format, cut-off, validation, access, retention, export and exit are agreed. The demo contains no real data and does not replace each project’s GDPR review.' }, { question: 'How are deposits, payments and no-shows approached?', answer: 'The demo shows advance information, acceptance and a breakdown with fictional data. Provider, policy, reconciliation, refunds and any real charge are validated per project.' }, { question: 'Do I have to change my whole operation?', answer: 'No. The conversation starts with today’s bottleneck and what your team already does well. Commercial scope is agreed before anything is developed or activated.' }] },
    lead: { eyebrow: 'Start with a conversation, not an account', title: 'Tell us what you want to organise. We will return a starting point.', body: 'Logic2B will review the operation you share and prepare an initial scope map for bookings, groups, events and the floor.', fields: { name: 'Name', restaurant: 'Restaurant', email: 'Work email', phone: 'Phone (optional)', level: 'What do you want to organise first?', message: 'What happens today? (optional)', privacy: 'I have read the privacy policy and accept that Logic2B uses these details to reply.' }, priorities: [{ value: 'basico', label: 'Direct booking on my website' }, { value: 'gestion', label: 'Daily service and groups' }, { value: 'inteligente', label: 'Events and private hire' }], submit: 'Send request', disabled: 'Sending is disabled in this demo. No data was sent or stored. You can contact Logic2B directly on WhatsApp.', invalid: 'Check the required fields and privacy acceptance.', failure: 'Connection failed. No data was sent or stored.', success: 'Request delivered to Logic2B. Keep the reference in case you need to contact us.', limited: 'You have reached the temporary request limit. Wait a minute or contact us on WhatsApp.', whatsapp: 'Talk on WhatsApp' },
    cookies: { text: 'This website loads no analytics. We only save your choice so we do not ask again.', accept: 'Allow future analytics', reject: 'Necessary only' },
    footer: { line: 'A booking, group and event proposition built around the real floor.', plans: 'Plans', restaurants: 'Restaurants', groups: 'Groups and events', legal: 'Legal', privacy: 'Privacy', cookies: 'Cookies', demo: 'Commercial demonstration · Not a production service' },
  },
} as const;

export const INFO_PAGES = {
  es: {
    planes: { eyebrow: 'Planes Logic Reserva', title: 'Tres formas de avanzar sin comprar de más.', intro: 'Básico muestra presencia y solicitudes; Gestión ordena la operación; Inteligente explora IA y automatización demostrativas. Logic2B define contigo qué alcance tendría sentido implantar.', points: ['Básico · web propia y recorrido de solicitud que una implantación podría enviar por email', 'Gestión · recorrido de organización con reservas, mesas, grupos, clientes e informes', 'Inteligente · IA determinista, automatizaciones simuladas, eventos y privatizaciones', 'Configuración y soporte sujetos al alcance comercial acordado'] },
    restaurantes: { eyebrow: 'Solución para restaurantes', title: 'La reserva puede empezar en tu web y terminar en la sala.', intro: 'La demo plantea una capa propia para convertir y ordenar el servicio. Datos, integraciones y puesta en marcha se concretan con Logic2B para cada proyecto.', points: ['Experiencia visual integrada en tu marca', 'Disponibilidad demostrada por mesa y turnos', 'Menús opcionales o cerrados', 'Estados legibles para el equipo de sala', 'Implantación y soporte por acordar'] },
    grupos: { eyebrow: 'Grupos y eventos', title: 'El evento deja de competir con la sala.', intro: 'La demo conecta aforo, menús, señal simulada y mesas consumidas. Logic2B valida contigo el recorrido y las integraciones antes de una implantación real.', points: ['Mesas combinables para grupos', 'Eventos que bloquean mesas en el escenario', 'Privatizaciones desde solicitud hasta señal simulada', 'Condiciones y desglose trazables en la demo', 'Alcance adaptado a tus formatos y condiciones'] },
    legal: { eyebrow: 'Información legal', title: 'Aviso legal de la demostración.', intro: 'Logic Reserva es una demostración comercial de Logic2B. No presta todavía un servicio de reservas, cobro o almacenamiento de datos.', points: ['Titular: Logic2B', 'Contacto: hola@logic2b.com', 'Las marcas Brasca, Vedra y Solane son ficticias', 'No existe relación contractual al explorar la demo'] },
    privacidad: { eyebrow: 'Privacidad', title: 'La demo no necesita tus datos para funcionar.', intro: 'No hay cuentas ni perfiles. El contacto transmite nombre, restaurante, email, teléfono opcional y el contexto que añadas para que Logic2B responda.', points: ['El formulario exige aceptación antes de enviar', 'Teléfono y mensaje son opcionales', 'La entrega usa un canal transaccional y limita abusos', 'El estado de las demos permanece en el navegador', 'Puedes solicitar acceso, rectificación o supresión por email'] },
    cookies: { eyebrow: 'Cookies', title: 'Solo estado local y con permiso.', intro: 'Actualmente no cargamos analítica ni publicidad. La preferencia se guarda localmente y se puede volver a configurar desde el pie de cualquier página comercial.', points: ['Sin cookies publicitarias', 'Sin analítica antes del consentimiento', 'Preferencia configurable de nuevo desde el footer', 'Cualquier medición futura será opcional'] },
  },
  en: {
    planes: { eyebrow: 'Logic Reserva plans', title: 'Three ways to move forward without overbuying.', intro: 'Basic shows presence and enquiries; Management organises the journey; Intelligent explores demo AI and automation. Logic2B defines with you what scope would make sense to implement.', points: ['Basic · owned website and an enquiry journey that an implementation could send by email', 'Management · demonstrated organisation with bookings, tables, groups, guests and reports', 'Intelligent · deterministic AI, simulated automation, events and private hire', 'Configuration and support subject to agreed commercial scope'] },
    restaurantes: { eyebrow: 'For restaurants', title: 'A booking can start on your website and end on the restaurant floor.', intro: 'The demo proposes an owned layer for conversion and service organisation. Data, integrations and launch are defined with Logic2B for each project.', points: ['Visually integrated brand experience', 'Demonstrated table and turn availability', 'Optional or fixed menus', 'Readable states for floor teams', 'Implementation and support to be agreed'] },
    grupos: { eyebrow: 'Groups and events', title: 'The event no longer competes with the dining room.', intro: 'The demo connects capacity, menus, a simulated deposit and consumed tables. Logic2B validates the journey and integrations with you before real implementation.', points: ['Combinable tables for groups', 'Events block tables in the scenario', 'Private hire from request to simulated deposit', 'Traceable demo terms and breakdown', 'Scope adapted to your formats and terms'] },
    legal: { eyebrow: 'Legal information', title: 'Demo legal notice.', intro: 'Logic Reserva is a Logic2B commercial demonstration. It does not yet provide booking, payment or data storage services.', points: ['Owner: Logic2B', 'Contact: hola@logic2b.com', 'Brasca, Vedra and Solane are fictional brands', 'Exploring the demo creates no contract'] },
    privacidad: { eyebrow: 'Privacy', title: 'The demo needs no personal data to work.', intro: 'There are no accounts or profiles. Contact sends your name, restaurant, email, optional phone number and any context you add so Logic2B can reply.', points: ['The form requires consent before sending', 'Phone and message are optional', 'Delivery uses a transactional channel and rate limits abuse', 'Demo state stays in the browser', 'Access, correction or deletion can be requested by email'] },
    cookies: { eyebrow: 'Cookies', title: 'Local state, and only with permission.', intro: 'We currently load no analytics or advertising. The preference is stored locally and can be configured again from the footer of any commercial page.', points: ['No advertising cookies', 'No analytics before consent', 'Preference can be configured again from the footer', 'Any future measurement will be optional'] },
  },
} as const;

export const COMMERCIAL_PAGE_DETAILS = {
  es: {
    planes: {
      metaTitle: 'Planes para digitalizar reservas | Logic Reserva',
      metaDescription: 'Demo de alcances para reservas: web propia, organización de sala y grupos, o eventos y automatización simulada. Implantación por definir.',
      chapters: [
        { title: 'Cuando la web informa, pero no convierte', body: 'Básico muestra cómo sustituir el “llámanos para reservar” por una experiencia propia. En una implantación, el restaurante podría recibir la solicitud sin enviar al cliente a una marca ajena.' },
        { title: 'Cuando coordinar ya pesa más que captar', body: 'Gestión ordena reservas, mesas, grupos y clientes antes del servicio. El valor no está en sumar pantallas, sino en dejar de reconstruir el día entre mensajes.' },
        { title: 'Cuando decidir tarde empieza a costar', body: 'Inteligente demuestra eventos, depósitos, automatizaciones simuladas y apoyo determinista a la decisión sobre el mismo contexto.' },
      ],
      outcomes: ['Empieza por un problema reconocible', 'Conserva un camino de crecimiento', 'Acuerda solo el alcance que usarás', 'Define con Logic2B qué requeriría una implantación'],
      offerings: [
        { title: 'Mantenimiento', body: 'Revisión y continuidad de la solución publicada, con responsabilidades, tiempos y canales concretados en la propuesta.', status: 'Alcance a definir' },
        { title: 'Desarrollo y mejoras', body: 'Evolución de recorridos, reglas o integraciones cuando el servicio real demuestre que merece la pena cambiar algo.', status: 'Alcance a definir' },
        { title: 'Servicios de lanzamiento', body: 'Acompañamiento para datos, dominio, validación, formación y salida a producción sin confundir demo con despliegue.', status: 'Alcance a definir' },
      ],
      faqs: [
        { question: '¿Puedo empezar por Básico y avanzar después?', answer: 'Sí. La escalera está pensada para añadir organización y decisión sin obligar al restaurante a adoptar toda la operativa desde el primer día.' },
        { question: '¿Hay un precio estándar para cada plan?', answer: 'La demo delimita el alcance funcional. La propuesta comercial depende de la web, los flujos, los puntos de venta y el acompañamiento que necesite cada restaurante.' },
        { question: '¿Qué plan encaja si ya tengo motor de reservas?', answer: 'Depende del cuello de botella. Si el problema está en grupos, eventos o coordinación de sala, Gestión o Inteligente pueden tener sentido aunque ya exista un canal de reserva.' },
        { question: '¿La configuración está incluida en la implantación?', answer: 'La demo no fija condiciones comerciales. En una implantación acordada, la propuesta debe detallar configuración, puesta en marcha, integraciones y soporte.' },
      ],
    },
    restaurantes: {
      metaTitle: 'Reservas online para restaurantes | Logic Reserva',
      metaDescription: 'Demo de reservas para restaurantes con identidad propia, disponibilidad por mesa, menús y operación de sala conectada en un mismo recorrido.',
      chapters: [
        { title: 'Antes de reservar, el cliente sigue en tu casa', body: 'La experiencia conserva el tono, la carta y la confianza de tu web. No obliga a saltar a otro dominio justo cuando el cliente está preparado para elegir.' },
        { title: 'Al confirmar, la promesa cabe en la sala', body: 'La disponibilidad responde a mesas, tamaños de grupo, turnos y menús. Lo que se ofrece online nace de la capacidad que el equipo puede atender.' },
        { title: 'Durante el servicio, nadie traduce el canal', body: 'Sala ve el origen, el estado y el contexto de cada reserva. El dato llega listo para actuar, no como otro mensaje que alguien tiene que interpretar.' },
      ],
      outcomes: ['Diseño orientado a la reserva directa', 'Menos conciliación antes del servicio', 'Modelo de datos por definir en cada implantación', 'Turnos, mesas y reglas validados con tu equipo'],
      faqs: [
        { question: '¿El widget puede respetar la marca del restaurante?', answer: 'Sí. La experiencia se plantea como parte de la web, con identidad, tono y recorrido propios, no como un iframe visualmente ajeno.' },
        { question: '¿Puede trabajar con menús cerrados?', answer: 'Sí. La demo muestra menús opcionales y cerrados vinculados a la reserva, de modo que cocina y sala conocen el compromiso antes del servicio.' },
        { question: '¿Logic Reserva cobra comisión por comensal?', answer: 'La demo no fija tarifas ni modelo de cobro. Cualquier cuota, coste transaccional, implantación y soporte debe aparecer en una propuesta comercial explícita.' },
        { question: '¿Tengo que configurar solo las mesas y los turnos?', answer: 'No. Si se acuerda una implantación, Logic2B revisa contigo el servicio y documenta qué configuración y soporte forman parte del alcance.' },
      ],
    },
    grupos: {
      metaTitle: 'Gestión de grupos y eventos | Logic Reserva',
      metaDescription: 'Demo de grupos, eventos y privatizaciones con menús, señales simuladas y mesas compartidas. La implantación se define por proyecto.',
      chapters: [
        { title: 'La solicitud deja de ser un mensaje suelto', body: 'Fechas, tamaño, formato y necesidades especiales entran con estructura. El equipo puede responder sin perseguir el contexto por correo y WhatsApp.' },
        { title: 'La propuesta se convierte en compromiso', body: 'Menú, condiciones y señal avanzan juntos. Cuando el cliente acepta, el espacio deja de ser una posibilidad y pasa a una decisión operativa.' },
        { title: 'El evento consume la sala que realmente ocupa', body: 'Las mesas bloqueadas dejan de ofrecerse en reserva ordinaria. Evento y restaurante comparten inventario para no vender dos veces la misma capacidad.' },
      ],
      outcomes: ['Seguimiento comercial demostrado en un recorrido', 'Señales y condiciones trazables en la demo', 'Aforo de eventos conectado a mesas del escenario', 'Alcance por validar alrededor de tus formatos reales'],
      faqs: [
        { question: '¿Sirve para grupos que combinan varias mesas?', answer: 'Sí. La demo permite proponer combinaciones según capacidad y conservar la asignación cuando el grupo avanza.' },
        { question: '¿Cómo se evita vender las mesas de un evento?', answer: 'Al publicar o confirmar el evento, las mesas consumidas se bloquean en el inventario compartido y dejan de aparecer como disponibilidad ordinaria.' },
        { question: '¿Puede gestionar una privatización completa?', answer: 'La experiencia cubre solicitud, propuesta, señal y bloqueo del espacio, con un estado entendible tanto para dirección como para sala.' },
        { question: '¿Quién adapta el circuito de grupos y eventos?', answer: 'En una implantación acordada, Logic2B define contigo solicitudes, formatos, menús, condiciones, señales, bloqueos y soporte. La demo no activa esos proveedores por sí sola.' },
      ],
    },
  },
  en: {
    planes: {
      metaTitle: 'Restaurant booking plans | Logic Reserva',
      metaDescription: 'Booking scope demo: owned website, floor and group organisation, or events and simulated automation. Implementation is defined per project.',
      chapters: [
        { title: 'When the website informs but does not convert', body: 'Basic shows how “call us to book” could become an owned experience. In an implementation, the restaurant could receive the enquiry without sending the guest to somebody else’s brand.' },
        { title: 'When coordination costs more than acquisition', body: 'Management organises bookings, tables, groups and guests before service. The value is not another screen, but no longer rebuilding the day from messages.' },
        { title: 'When late decisions start costing money', body: 'Intelligent demonstrates events, deposits, simulated automation and deterministic decision support in the same context.' },
      ],
      outcomes: ['Start with a recognisable problem', 'Keep a clear growth path', 'Agree only the scope you will use', 'Define with Logic2B what an implementation would require'],
      offerings: [
        { title: 'Maintenance', body: 'Review and continuity for the published solution, with responsibilities, timing and channels set out in the proposal.', status: 'Scope to define' },
        { title: 'Development and improvements', body: 'Evolution of journeys, rules or integrations when real service shows that a change is worth making.', status: 'Scope to define' },
        { title: 'Launch services', body: 'Support for data, domain, validation, training and production release without confusing a demo with deployment.', status: 'Scope to define' },
      ],
      faqs: [
        { question: 'Can I start with Basic and move up later?', answer: 'Yes. The path adds organisation and decision support without forcing the restaurant to adopt the full operation on day one.' },
        { question: 'Is there a standard price for each plan?', answer: 'The demo defines functional scope. A commercial proposal depends on the website, workflows, locations and support each restaurant needs.' },
        { question: 'Which plan fits if I already have a booking engine?', answer: 'It depends on the bottleneck. If groups, events or floor coordination are the problem, Management or Intelligent may fit even with an existing booking channel.' },
        { question: 'Is configuration included in implementation?', answer: 'The demo sets no commercial terms. An agreed implementation proposal must detail configuration, launch, integrations and support.' },
      ],
    },
    restaurantes: {
      metaTitle: 'Online restaurant bookings | Logic Reserva',
      metaDescription: 'Restaurant booking demo with an owned identity, table availability, menus and floor operations connected in one journey.',
      chapters: [
        { title: 'Before booking, the guest stays in your home', body: 'The experience keeps the tone, menu and trust of your website. Guests do not jump to another domain just as they are ready to choose.' },
        { title: 'At confirmation, the promise fits the floor', body: 'Availability follows tables, party sizes, turns and menus. What is offered online comes from the capacity your team can actually serve.' },
        { title: 'During service, nobody translates the channel', body: 'Floor teams see the source, status and context of each booking. Data arrives ready for action, not as another message somebody must interpret.' },
      ],
      outcomes: ['A design oriented towards direct booking', 'Less reconciliation before service', 'A data model to define per implementation', 'Turns, tables and rules validated with your team'],
      faqs: [
        { question: 'Can the widget match the restaurant brand?', answer: 'Yes. The experience is designed as part of the website, with its own identity, tone and journey rather than a visually foreign iframe.' },
        { question: 'Can it work with fixed menus?', answer: 'Yes. The demo shows optional and fixed menus linked to the booking, so kitchen and floor teams know the commitment before service.' },
        { question: 'Does Logic Reserva charge per guest?', answer: 'The demo sets no pricing or charging model. Any subscription, transaction cost, implementation and support must appear in an explicit commercial proposal.' },
        { question: 'Do I have to configure tables and turns on my own?', answer: 'No. If an implementation is agreed, Logic2B reviews service with you and documents which configuration and support are in scope.' },
      ],
    },
    grupos: {
      metaTitle: 'Restaurant group and event management | Logic Reserva',
      metaDescription: 'Demo of groups, events and private hire with menus, simulated deposits and shared tables. Implementation is defined per project.',
      chapters: [
        { title: 'The enquiry stops being a loose message', body: 'Dates, party size, format and special needs arrive with structure. Your team can respond without chasing context across email and WhatsApp.' },
        { title: 'The proposal becomes a commitment', body: 'Menu, terms and deposit move together. Once the guest accepts, the space becomes an operational decision rather than a possibility.' },
        { title: 'The event consumes the floor it actually uses', body: 'Blocked tables stop appearing in ordinary booking availability. Events and restaurant service share inventory so the same capacity is never sold twice.' },
      ],
      outcomes: ['Commercial follow-up demonstrated in one journey', 'Traceable demo deposits and terms', 'Event capacity connected to scenario tables', 'Scope to validate around your real formats'],
      faqs: [
        { question: 'Does it work for groups combining several tables?', answer: 'Yes. The demo proposes combinations by capacity and keeps the assignment as the group progresses.' },
        { question: 'How do events stop tables being sold twice?', answer: 'When the event is published or confirmed, its tables are blocked in shared inventory and disappear from ordinary availability.' },
        { question: 'Can it manage full private hire?', answer: 'The experience covers enquiry, proposal, deposit and space block with a status both management and floor teams can understand.' },
        { question: 'Who adapts the group and event journey?', answer: 'In an agreed implementation, Logic2B defines enquiry types, formats, menus, terms, deposits, blocks and support with you. The demo activates no providers by itself.' },
      ],
    },
  },
} as const;

export type InfoPageKey = keyof typeof INFO_PAGES.es;
export type CommercialPageKey = keyof typeof COMMERCIAL_PAGE_DETAILS.es;
