export const BOOKING_AMENDMENT_COPY = {
  es: {
    edit: 'Editar reserva',
    title: 'Editar reserva',
    body: 'Revisa las nuevas condiciones y la mesa antes de guardar el cambio.',
    localOnly: 'Cambio local de demostración · No se envían mensajes ni se realizan cobros.',
    date: 'Fecha de la reserva',
    shift: 'Turno de la reserva',
    time: 'Hora de la reserva',
    party: 'Personas',
    lunch: 'Comida',
    dinner: 'Cena',
    table: 'Mesa o combinación',
    chooseTable: 'Selecciona una mesa disponible',
    capacity: 'plazas',
    people: 'personas',
    minutes: 'min',
    before: 'Antes del cambio',
    after: 'Después del cambio',
    duration: 'Duración prevista',
    pendingAssignment: 'Pendiente de elegir mesa',
    incompleteConditions: 'Completa la fecha, la hora y el número de personas.',
    noChanges: 'Modifica las condiciones o la asignación de mesa para guardar.',
    depositLocked: 'Esta reserva tiene un registro de depósito. Solo puedes cambiar las mesas; fecha, hora, duración y personas conservan las condiciones aceptadas.',
    attendanceWarning: 'Al cambiar la fecha, la hora, la duración o las personas, se invalidarán los enlaces locales de confirmación de asistencia de esta reserva. No se enviará ningún mensaje al cliente.',
    noTables: 'No hay mesas disponibles para estas condiciones. Prueba otra franja o ajusta el grupo.',
    noTablesWithDeposit: 'No hay mesas disponibles para las condiciones aceptadas de esta reserva. Cancela la edición para conservarlas y revisar la asignación más adelante.',
    noShifts: 'No hay turnos configurados para este restaurante.',
    readOnly: 'Tu rol puede consultar esta reserva, pero no editarla.',
    closedBooking: 'Solo se pueden editar reservas pendientes o confirmadas.',
    invalidDate: 'Selecciona una fecha válida para la reserva.',
    invalidParty: 'Indica un número entero de personas entre 1 y 40.',
    invalidTime: 'Selecciona un turno y una hora válida dentro de ese turno.',
    missingTable: 'Selecciona una mesa disponible antes de guardar.',
    assignmentChanged: 'La mesa elegida ya no está disponible para estas condiciones. Tus datos se conservan: elige otra mesa o cambia la franja.',
    assignmentChangedWithDeposit: 'La mesa elegida ya no está disponible. Elige otra mesa disponible o cancela la edición; las condiciones aceptadas del depósito se conservan.',
    saveFailed: 'No se han guardado los cambios. La reserva, la disponibilidad o tu permiso han cambiado. Tus datos se conservan: revisa la asignación o cancela y vuelve a abrir la edición para cargar la reserva actual.',
    save: 'Guardar cambios',
    cancel: 'Cancelar edición',
    saved: 'Cambios de la reserva guardados en esta demo.',
  },
  en: {
    edit: 'Edit booking',
    title: 'Edit booking',
    body: 'Review the new details and table before saving the change.',
    localOnly: 'Local demo change · No messages are sent and no charges are made.',
    date: 'Booking date',
    shift: 'Booking shift',
    time: 'Booking time',
    party: 'Guests',
    lunch: 'Lunch',
    dinner: 'Dinner',
    table: 'Table or combination',
    chooseTable: 'Choose an available table',
    capacity: 'seats',
    people: 'guests',
    minutes: 'min',
    before: 'Before the change',
    after: 'After the change',
    duration: 'Estimated duration',
    pendingAssignment: 'Choose a table',
    incompleteConditions: 'Complete the date, time and number of guests.',
    noChanges: 'Change the booking details or table assignment to save.',
    depositLocked: 'This booking has a deposit record. You can only change its tables; the date, time, duration and number of guests retain the accepted terms.',
    attendanceWarning: 'Changing the date, time, duration or number of guests will invalidate this booking’s local attendance confirmation links. No message will be sent to the guest.',
    noTables: 'No tables are available for these details. Try another time or adjust the party.',
    noTablesWithDeposit: 'No tables are available for this booking’s accepted terms. Cancel editing to preserve them and review the assignment later.',
    noShifts: 'No shifts are configured for this restaurant.',
    readOnly: 'Your role can view this booking but cannot edit it.',
    closedBooking: 'Only pending or confirmed bookings can be edited.',
    invalidDate: 'Select a valid booking date.',
    invalidParty: 'Enter a whole number of guests between 1 and 40.',
    invalidTime: 'Select a shift and a valid time within that shift.',
    missingTable: 'Choose an available table before saving.',
    assignmentChanged: 'The selected table is no longer available for these details. Your entries are preserved: choose another table or change the time.',
    assignmentChangedWithDeposit: 'The selected table is no longer available. Choose another available table or cancel editing; the accepted deposit terms are preserved.',
    saveFailed: 'The changes were not saved. The booking, availability or your permission has changed. Your entries are preserved: review the assignment, or cancel and reopen editing to load the current booking.',
    save: 'Save changes',
    cancel: 'Cancel editing',
    saved: 'Booking changes saved in this demo.',
  },
} as const;
