import type { BookingSource, BookingStatus } from '@logic-reserva/domain';

export type DashboardLocale = 'es' | 'en';
export type DashboardView = 'servicio' | 'plano' | 'reservas' | 'espera' | 'clientes' | 'informes' | 'ajustes';

export interface DashboardText {
  readonly es: string;
  readonly en: string;
}

const text = (es: string, en: string): DashboardText => ({ es, en });

export const DASHBOARD_VIEWS = [
  { id: 'servicio', label: text('Servicio', 'Service') },
  { id: 'plano', label: text('Plano', 'Floor plan') },
  { id: 'reservas', label: text('Reservas', 'Bookings') },
  { id: 'espera', label: text('Espera', 'Waitlist') },
  { id: 'clientes', label: text('Clientes', 'Guests') },
  { id: 'informes', label: text('Informes', 'Reports') },
  { id: 'ajustes', label: text('Ajustes', 'Settings') },
] as const satisfies readonly { id: DashboardView; label: DashboardText }[];

export const DASHBOARD_COPY = {
  product: text('Logic Reserva · Gestión', 'Logic Reserva · Manage'),
  backToWebsite: text('Volver a la web', 'Back to website'),
  fictional: text('Demostración ficticia · Los cambios solo se guardan en este navegador', 'Fictional demonstration · Changes are saved only in this browser'),
  reset: text('Restablecer demo', 'Reset demo'),
  resetDone: text('Demo restablecida con los datos iniciales.', 'Demo reset to its initial data.'),
  minutes: text('min', 'min'),
  service: {
    eyebrow: text('Vista de servicio', 'Service view'),
    title: text('La sala, de un vistazo.', 'The dining room at a glance.'),
    body: text('Consulta la ocupación por mesa y franja de 15 minutos. Las reservas activas ocupan el inventario durante toda su estancia.', 'Review occupancy by table and 15-minute slot. Active bookings occupy inventory for their full duration.'),
    date: text('Fecha del servicio', 'Service date'),
    shift: text('Turno', 'Shift'),
    lunch: text('Comida', 'Lunch'),
    dinner: text('Cena', 'Dinner'),
    tables: text('Mesas', 'Tables'),
    empty: text('No hay reservas activas en este servicio.', 'There are no active bookings in this service.'),
    free: text('Libre', 'Free'),
  },
  reservations: {
    eyebrow: text('Libro de reservas', 'Booking book'),
    title: text('Reservas y próximos pasos.', 'Bookings and next steps.'),
    body: text('Confirma solicitudes y acompaña cada mesa desde la llegada hasta el cierre del servicio.', 'Confirm requests and move each table from arrival through the end of service.'),
    all: text('Todas', 'All'),
    active: text('Activas', 'Active'),
    closed: text('Cerradas', 'Closed'),
    guest: text('Reserva', 'Booking'),
    dateTime: text('Fecha y hora', 'Date and time'),
    party: text('Grupo', 'Party'),
    assignment: text('Mesa y menú', 'Table and menu'),
    status: text('Estado', 'Status'),
    actions: text('Siguiente acción', 'Next action'),
    people: text('personas', 'guests'),
    noMenu: text('Sin menú cerrado', 'No fixed menu'),
    noActions: text('Sin acciones pendientes', 'No pending actions'),
    empty: text('No hay reservas en este filtro.', 'There are no bookings in this filter.'),
  },
  floor: {
    eyebrow: text('Plano y grupos', 'Floor plan and groups'),
    title: text('Combina la sala sin perder el servicio.', 'Combine the room without losing sight of service.'),
    body: text('El plano cruza cada mesa con el inventario real. El recorrido de grupo usa únicamente combinaciones contiguas calculadas por el dominio.', 'The floor plan checks every table against live inventory. The group journey only uses adjacent combinations calculated by the domain.'),
    request: text('Solicitud de grupo', 'Group request'),
    requested: text('Nueva solicitud', 'New request'),
    tablesAssigned: text('Mesas asignadas', 'Tables assigned'),
    menuAssigned: text('Menú asignado', 'Menu assigned'),
    confirmed: text('Grupo confirmado', 'Group confirmed'),
    date: text('Fecha', 'Date'),
    time: text('Hora', 'Time'),
    party: text('Grupo', 'Party'),
    people: text('personas', 'guests'),
    chooseModeTitle: text('¿Cómo quieres explorar el recorrido?', 'How would you like to explore the journey?'),
    chooseModeBody: text('El modo guiado acompaña los tres momentos clave. El modo libre deja todas las decisiones abiertas.', 'Guided mode walks through the three key moments. Free mode leaves every decision open.'),
    guided: text('Empezar recorrido guiado', 'Start guided journey'),
    guidedBody: text('Solicitud → combinación → menú y confirmación.', 'Request → combination → menu and confirmation.'),
    free: text('Explorar libremente', 'Explore freely'),
    freeBody: text('Abre el plano completo sin indicaciones.', 'Open the full floor plan without prompts.'),
    tourLabel: text('Recorrido Vedra', 'Vedra journey'),
    tourSteps: [text('Solicitud', 'Request'), text('Combinar mesas', 'Combine tables'), text('Menú y confirmar', 'Menu and confirm')],
    stepOneTitle: text('Una mesa no basta para ocho.', 'One table is not enough for eight.'),
    stepOneBody: text('Revisa la solicitud y pide al motor opciones contiguas con capacidad suficiente.', 'Review the request and ask the engine for adjacent options with enough capacity.'),
    findCombination: text('Proponer combinaciones', 'Suggest combinations'),
    stepTwoTitle: text('Elige dos mesas que sí trabajan juntas.', 'Choose two tables that work together.'),
    stepTwoBody: text('Todas las opciones son mínimas, pertenecen al mismo espacio y están libres para la franja solicitada.', 'Every option is minimal, belongs to one space and is free for the requested slot.'),
    noCombinations: text('No hay combinaciones disponibles para esta franja.', 'No combinations are available for this slot.'),
    chooseCombination: text('Elegir combinación', 'Choose combination'),
    selectedCombination: text('Combinación elegida', 'Selected combination'),
    stepThreeTitle: text('Cierra el acuerdo con un menú.', 'Close the agreement with a menu.'),
    stepThreeBody: text('Asigna el menú de grupo y confirma: la reserva pasará a ocupar ambas mesas en todo el gestor.', 'Assign the group menu and confirm: the booking will occupy both tables throughout the workspace.'),
    menu: text('Menú para el grupo', 'Group menu'),
    selectMenu: text('Selecciona un menú', 'Select a menu'),
    perPerson: text('por persona', 'per guest'),
    confirmGroup: text('Confirmar grupo de 8', 'Confirm party of 8'),
    completedTitle: text('Grupo confirmado y mesas bloqueadas.', 'Group confirmed and tables blocked.'),
    completedBody: text('La reserva ya aparece en Servicio y Reservas con las dos mesas y el menú asignados.', 'The booking now appears in Service and Bookings with both tables and the assigned menu.'),
    openService: text('Ver en Servicio', 'View in Service'),
    restartJourney: text('Reiniciar recorrido', 'Restart journey'),
    floorTitle: text('Plano por espacios', 'Floor plan by space'),
    floorBody: text('Selecciona una mesa para ver capacidad, conexiones y ocupación.', 'Select a table to see capacity, connections and occupancy.'),
    freeTable: text('Libre', 'Free'),
    occupiedTable: text('Ocupada', 'Occupied'),
    selectedTable: text('Seleccionada', 'Selected'),
    groupTable: text('Grupo confirmado', 'Confirmed group'),
    tableDetail: text('Detalle de mesa', 'Table details'),
    capacity: text('Capacidad', 'Capacity'),
    seats: text('plazas', 'seats'),
    space: text('Espacio', 'Space'),
    connectsWith: text('Combina con', 'Combines with'),
    noConnections: text('Sin conexiones', 'No connections'),
    occupancy: text('Ocupación', 'Occupancy'),
    available: text('Disponible para este grupo', 'Available for this party'),
    selectedHint: text('Selecciona una mesa del plano.', 'Select a table on the floor plan.'),
  },
  customers: {
    eyebrow: text('Clientes', 'Guests'),
    title: text('Contexto antes de recibir.', 'Context before welcoming.'),
    body: text('Una ficha básica construida desde las reservas de esta demo, sin base de datos ni perfiles reales.', 'A basic record built from this demo’s bookings, with no database or real profiles.'),
    bookings: text('reservas', 'bookings'),
    covers: text('comensales', 'covers'),
    lastVisit: text('Última reserva', 'Latest booking'),
    contact: text('Contacto', 'Contact'),
    notAvailable: text('No disponible', 'Not available'),
    source: text('Origen reciente', 'Latest source'),
    groupRequest: text('Solicitud de grupo activa', 'Active group request'),
  },
  settings: {
    eyebrow: text('Configuración', 'Settings'),
    title: text('La operación que sostiene la reserva.', 'The operation behind every booking.'),
    body: text('Turnos, espacios y menús se muestran en lectura para explicar el nivel Gestión sin fingir una configuración conectada.', 'Shifts, spaces and menus are shown read-only to explain the Manage tier without pretending configuration is connected.'),
    maturity: text('Lectura · Demo funcional', 'Read only · Functional demo'),
    shifts: text('Turnos', 'Shifts'),
    spaces: text('Espacios y mesas', 'Spaces and tables'),
    menus: text('Menús online', 'Online menus'),
    firstSeating: text('Primera reserva', 'First seating'),
    lastSeating: text('Última reserva', 'Last seating'),
    tables: text('mesas', 'tables'),
    privatizable: text('Privatizable', 'Private hire enabled'),
    notPrivatizable: text('No privatizable', 'Private hire disabled'),
    online: text('Reservable online', 'Bookable online'),
    offline: text('Solo equipo', 'Team only'),
  },
  source: {
    widget: text('Desde la web demo', 'From the demo website'),
    phone: text('Teléfono', 'Phone'),
    walkin: text('Sin reserva', 'Walk-in'),
    fixture: text('Reserva inicial', 'Initial booking'),
  } satisfies Record<BookingSource, DashboardText>,
  status: {
    pending: text('Pendiente', 'Pending'),
    confirmed: text('Confirmada', 'Confirmed'),
    seated: text('Sentada', 'Seated'),
    finished: text('Finalizada', 'Finished'),
    no_show: text('No presentado', 'No-show'),
    cancelled: text('Cancelada', 'Cancelled'),
  } satisfies Record<BookingStatus, DashboardText>,
  action: {
    pending: text('Marcar pendiente', 'Mark pending'),
    confirmed: text('Confirmar', 'Confirm'),
    seated: text('Sentar', 'Seat'),
    finished: text('Finalizar', 'Finish'),
    no_show: text('No presentado', 'No-show'),
    cancelled: text('Cancelar', 'Cancel'),
  } satisfies Record<BookingStatus, DashboardText>,
} as const;

export const dashboardText = (value: DashboardText, locale: DashboardLocale): string => value[locale];

export function dashboardView(value: string | null): DashboardView {
  return DASHBOARD_VIEWS.some((view) => view.id === value) ? value as DashboardView : 'servicio';
}
