export const MANUAL_BOOKING_COPY = {
  es: {
    title: 'Nueva reserva telefónica',
    create: 'Nueva reserva',
    body: 'Registra la llamada y asigna una mesa disponible para toda la estancia.',
    localOnly: 'Reserva local de demostración · Sin depósitos, cobros ni mensajes al cliente.',
    name: 'Nombre del cliente',
    phone: 'Teléfono (opcional)',
    email: 'Email (opcional)',
    date: 'Fecha de la reserva',
    shift: 'Turno de la reserva',
    lunch: 'Comida',
    dinner: 'Cena',
    time: 'Hora de la reserva',
    party: 'Personas',
    menu: 'Menú (opcional)',
    noMenu: 'Sin menú cerrado',
    table: 'Mesa o combinación',
    chooseTable: 'Selecciona una mesa disponible',
    capacity: 'plazas',
    duration: 'Duración prevista',
    assignment: 'Asignación de mesa',
    pendingAssignment: 'Pendiente de elegir mesa',
    minutes: 'min',
    noTables: 'No hay mesas disponibles para esta fecha, hora y número de personas. Prueba otra franja o ajusta el grupo.',
    noShifts: 'No hay turnos configurados para este restaurante.',
    readOnly: 'Tu rol puede consultar las reservas, pero no crear una nueva.',
    invalidName: 'Escribe el nombre del cliente, con un máximo de 120 caracteres.',
    invalidEmail: 'Revisa el email o deja este campo vacío.',
    invalidPhone: 'El teléfono debe tener un máximo de 40 caracteres.',
    invalidDate: 'Selecciona una fecha válida para la reserva.',
    invalidParty: 'Indica un número entero de personas entre 1 y 40.',
    invalidTime: 'Selecciona un turno y una hora válida dentro de ese turno.',
    invalidMenu: 'Selecciona un menú disponible o deja la reserva sin menú cerrado.',
    missingTable: 'Selecciona una mesa disponible antes de guardar.',
    inventoryChanged: 'La mesa elegida ya no está disponible. Tus datos se conservan: elige otra mesa o cambia la franja.',
    saveConflict: 'No se ha podido guardar la reserva. Tus datos se conservan: revisa la mesa elegida y vuelve a intentarlo.',
    save: 'Confirmar reserva telefónica',
    cancel: 'Cancelar alta',
    saved: 'Reserva telefónica confirmada en esta demo.',
  },
  en: {
    title: 'New phone booking',
    create: 'New booking',
    body: 'Record the call and assign an available table for the full visit.',
    localOnly: 'Local demo booking · No deposits, charges or messages to the guest.',
    name: 'Guest name',
    phone: 'Phone (optional)',
    email: 'Email (optional)',
    date: 'Booking date',
    shift: 'Booking shift',
    lunch: 'Lunch',
    dinner: 'Dinner',
    time: 'Booking time',
    party: 'Guests',
    menu: 'Menu (optional)',
    noMenu: 'No fixed menu',
    table: 'Table or combination',
    chooseTable: 'Choose an available table',
    capacity: 'seats',
    duration: 'Estimated duration',
    assignment: 'Table assignment',
    pendingAssignment: 'Choose a table',
    minutes: 'min',
    noTables: 'No tables are available for this date, time and party size. Try another time or adjust the party.',
    noShifts: 'No shifts are configured for this restaurant.',
    readOnly: 'Your role can view bookings but cannot create one.',
    invalidName: 'Enter the guest name, using no more than 120 characters.',
    invalidEmail: 'Check the email address or leave this field empty.',
    invalidPhone: 'The phone number must have no more than 40 characters.',
    invalidDate: 'Select a valid booking date.',
    invalidParty: 'Enter a whole number of guests between 1 and 40.',
    invalidTime: 'Select a shift and a valid time within that shift.',
    invalidMenu: 'Select an available menu or leave the booking without a fixed menu.',
    missingTable: 'Choose an available table before saving.',
    inventoryChanged: 'The selected table is no longer available. Your details are preserved: choose another table or change the time.',
    saveConflict: 'The booking could not be saved. Your details are preserved: review the selected table and try again.',
    save: 'Confirm phone booking',
    cancel: 'Cancel booking entry',
    saved: 'Phone booking confirmed in this demo.',
  },
} as const;
